spring:
  profiles:
    active: dev
  application:
    name: platzi-play-by-hector
server:
  servlet:
    context-path: /platzi-play/api
langchain4j:
  open-ai:
    chat-model:
      model-name: gpt-4o-mini

